#1064 [BACKOFFICE] [Bugs] Product Variations - show images with thumbnail
nashtech-garage/yas pull request #1093
Opened 2024-09-26 10:34 UTC by nashtech-tuannguyenhuu1

#1064 [BACKOFFICE] [Bugs] Product Variations - show images with thumbnail

2024-09-26 10:42 UTC, nashtech-huyphamphu approved these changes

2024-09-26 10:49 UTC, VanCongBang approved these changes

2024-09-26 14:37 UTC, VanCongBang requested changes
![image](https://github.com/user-attachments/assets/09354bc4-3dfe-4e55-9aa9-ad4d1bd378de)

Please make sure clear Sonar issue before merging

2024-09-27 03:52 UTC, VanCongBang approved these changes

2024-09-27 06:16 UTC, merged