Backoffice/optimize validation tab general information of create and edit products form
nashtech-garage/yas pull request #252
Opened 2023-02-09 09:49 UTC by khoahd7621

When creating a product, user can create a successful product with all empty fields empty, so I try to add some validation before submitting form to request to create a new product.
- Create Select component for re-use
- Add some necessary props for Input component to operate validation
- Optimize code of ProductGeneralInformation and ProductUpdateInformation component
- Fixed a warning in list products page

2023-02-09 10:00 UTC, thiennn requested changes
The name: Input and Select are too general. Please find more specific names

2023-02-09 13:24 UTC, khoahd7621 commented
> The name: Input and Select are too general. Please find more specific names

I keep the name "Input" because this component can be re-used everywhere we want to put an input tag.
Component "Select" has the same purpose for reusable, and I've changed the name "Select" to "SelectOption," more specifically for readability purposes.

If you have any suggestions, please refer them to me! Thanks!

2023-02-10 04:33 UTC, khoahd7621 commented
@thiennn I have updated generic type for Input and SelectOption components. Please review it again and give me your feedback. Thank you.

2023-02-10 06:05 UTC, thiennn approved these changes

2023-02-10 06:06 UTC, merged