Manage State Or Provinces
nashtech-garage/yas pull request #532
Opened 2023-03-28 09:15 UTC by DieuNguyenThi

2023-03-28 09:46 UTC, duccaominh commented on backoffice/modules/system/components/CountryGeneralInformation.tsx
> +import { Input } from 'common/items/Input';
good approach 🤗

2023-03-28 09:48 UTC, duccaominh commented on location/src/main/java/com/yas/location/controller/CountryController.java
> +    @GetMapping({""})
```Java
@GetMapping
```

2023-03-28 09:54 UTC, duccaominh commented on location/src/main/java/com/yas/location/service/StateOrProvinceService.java
> +                .country(country)
Do we really need to load the whole country entity here

2023-03-28 09:55 UTC, duccaominh requested changes
hi @DieuNguyenThi  please review the refactor code on backend side for me

2023-03-29 01:36 UTC, chanhnguyen6975 approved these changes

2023-03-29 03:21 UTC, duccaominh approved these changes

2023-03-29 03:22 UTC, merged