T41 add Unit test for get category list and get detail category
nashtech-garage/yas pull request #83
Opened 2022-09-16 11:24 UTC by PhaciusPhat

unit test when getting valid categories successfully
![image](https://user-images.githubusercontent.com/55187035/190628400-c578ece6-d3ed-45f1-9fc5-d4d2be4f330e.png)
unit test when getting a valid category 
![image](https://user-images.githubusercontent.com/55187035/190628442-f1da322f-4c9c-4568-a996-bc256dadb258.png)
unit test when getting a category with not found Id 
![image](https://user-images.githubusercontent.com/55187035/190628474-43d12906-37a6-4d19-b051-645118a4becd.png)

2022-09-17 04:42 UTC, PhaciusPhat commented
create category with parentId and without parentId
![image](https://user-images.githubusercontent.com/55187035/190840777-c3b639e8-ae3a-4876-99b4-ea5007fd90f6.png)
create category with invalid parentId
![image](https://user-images.githubusercontent.com/55187035/190840779-2d14873f-b8e2-4e50-899a-921107fb65da.png)

2022-09-19 02:31 UTC, thiennn requested changes

2022-09-19 02:31 UTC, thiennn commented on product/src/test/java/com/yas/product/controller/CategoryControllerTest.java
> +
please help remove 1 blank line

2022-09-19 02:31 UTC, thiennn commented on product/src/test/java/com/yas/product/controller/CategoryControllerTest.java
> +
please help remove 1 blank line

2022-09-19 02:31 UTC, thiennn commented on product/src/test/java/com/yas/product/controller/CategoryControllerTest.java
> +        // create captor data when we send it to save method
we shouldn't add comment for obvious code

2022-09-19 04:42 UTC, thiennn approved these changes

2022-09-19 04:42 UTC, merged