[Product] Increase readability and maintainability of ProductService(#943)
nashtech-garage/yas pull request #962
Opened 2024-08-28 16:33 UTC by minhtranq-nashtechglobal

2024-08-30 03:29 UTC, minhtridn2001 requested changes
Hi @minhtranq-nashtechglobal,
Thanks for your effort in making these changes.
However, there are still many `saveAllAndFlush` methods being used in product/service/ProductService. Is there any reason for not replacing them with `saveAll`?
For instance:  #com/yas/product/service/ProductService.java#L444
```java
        productRelatedRepository.saveAllAndFlush(newProductRelations);
```
Also, please amend the commit message as it doesn't align with the changes made.

Thanks!

2024-08-30 07:47 UTC, minhtranq-nashtechglobal commented
Hi a @minhtridn2001
Thanks for your comments, I have adjuested according to your comments.

2024-09-04 02:03 UTC, minhtridn2001 reviewed
Thanks, @minhtranq-nashtechglobal
Could you please resolve the conflicts and the failed test case?

2024-09-04 06:32 UTC, minhtridn2001 approved these changes

2024-09-05 09:03 UTC, mochacr0 approved these changes

2024-09-09 05:42 UTC, merged